drivers: soc: metrics: fix missing type specifier
drivers/soc/google/vh/kernel/metrics/init_metrics.c:11:8: error:
type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
extern perf_metrics_init(struct kobject *metrics_kobj);
~~~~~~ ^
int
drivers/soc/google/vh/kernel/metrics/init_metrics.c:12:8: error:
type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
extern thermal_metrics_init(struct kobject *metrics_kobj);
~~~~~~ ^
int
2 errors generated.

Change-Id: Ie2dd30578c0ac352bf9c3c9bfec465b616a630c3